import type { ReproManifest } from './types.js';

export function renderReproMarkdown(manifest: ReproManifest): string {
  const cmd = manifest.command.command.map((part) => JSON.stringify(part)).join(' ');
  const fixtures = manifest.fixtures.length
    ? manifest.fixtures.map((f) => `- \`${f.bundledPath}\` (${f.bytes} bytes from \`${f.source}\`)`).join('\n')
    : '- No fixtures bundled.';
  const redactions = manifest.redactions.length ? manifest.redactions.map((r) => `- ${r}`).join('\n') : '- none';
  return `# Repro bundle\n\nGenerated by bugrepro on ${manifest.createdAt}.\n\n## Command\n\n\`\`\`bash\n${cmd}\n\`\`\`\n\nExit code: ${manifest.command.exitCode ?? 'signal ' + manifest.command.signal}\n\n## Replay\n\n\`\`\`bash\nbugrepro replay .\n\`\`\`\n\n## Environment\n\n- platform: ${manifest.environment.platform}/${manifest.environment.arch}\n- node: ${manifest.environment.node}\n- npm: ${manifest.environment.npm ?? 'unknown'}\n- git: ${manifest.environment.git ?? 'unknown'}\n\n## Git\n\n- root: ${manifest.git.root ?? 'unknown'}\n- branch: ${manifest.git.branch ?? 'unknown'}\n- commit: ${manifest.git.commit ?? 'unknown'}\n- dirty: ${manifest.git.dirty ?? 'unknown'}\n\n## Fixtures\n\n${fixtures}\n\n## Redactions applied\n\n${redactions}\n\n## Captured stdout\n\n\`\`\`text\n${manifest.command.stdout}\n\`\`\`\n\n## Captured stderr\n\n\`\`\`text\n${manifest.command.stderr}\n\`\`\`\n`;
}
